# -*- coding: utf-8 -*-
"""Plus Minus.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xKm5U5_i3xm368ieU9h1B09epvvQK3PG
"""

#!/bin/python3

import math
import os
import random
import re
import sys

def plusMinus(arr):

    n = len(arr)
    positif = len(tuple(filter(lambda x:x>0 , arr)))
    negatif = len(tuple(filter(lambda x:x<0, arr)))
    nol = len(tuple(filter(lambda x:x==0, arr)))
    print(positif/n)
    print(negatif/n)
    print(nol/n)

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)